# Dockerfile for building LogicTech Media Server music volumes
#
# John Tarlton
#
# docker build --tag="jtarlton/music" .
# docker run --name music -t jtarlton/music true
#

FROM busybox

MAINTAINER John Tarlton 

RUN mkdir /music

VOLUME /music
